[package]
name = "snow-ui"
version = { workspace = true }
authors = ["clia <helloclia@gmail.com>"]
edition = { workspace = true }
rust-version = { workspace = true }
description = "Snow UI core library"
homepage = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
categories = { workspace = true }

[dependencies]
anyhow = { workspace = true }
snow-ui-macros = { workspace = true }
tokio = { workspace = true, features = ["time", "rt"] }
futures = { workspace = true }
inventory = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock"] }
masonry = { git = "https://github.com/linebender/xilem.git", branch = "main" }
masonry_winit = { git = "https://github.com/linebender/xilem.git", branch = "main" }
image = { version = "0.25", default-features = false, features = ["png"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3"
wasm-bindgen-futures = "0.4"
gloo-timers = "0.3"
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = [
	"Window",
	"Document",
	"Element",
	"Node",
	"HtmlElement",
	"Event",
	"EventTarget",
] }

[[example]]
name = "lovely_girl"
path = "../../examples/lovely_girl.rs"

[[example]]
name = "clock"
path = "../../examples/clock.rs"

[[example]]
name = "timer"
path = "../../examples/timer.rs"

[[example]]
name = "click"
path = "../../examples/click.rs"

[[example]]
name = "masonry_button"
path = "../../examples/masonry_button.rs"

[[example]]
name = "login"
path = "../../examples/login.rs"
